# Generated by Django 4.0.1 on 2022-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/phone.jpg', null=True, upload_to=''),
        ),
    ]
